### ISSUE TITLE
[Suggestion] Automated boundary/wall system for overworld

### ISSUE THREAD

**Issue by ElijahZAwesome** [AddMGH/Undertale-3DS#1]
To make it easier to add collisions, instead of manually programming every wall in the game, instead we use a system that goes like this:

Whenever you walk, the engine looks at the surrounding walls and checks for a certain color, and depending on the current area, there will be a list of colors that = a wall to create automated boundaries, with a blacklist for objects, such as flowers, that have custom or no boundaries.

**Comment by AddMGH** [comment]
There are modules for collisions that work far better than via spaghetti coding.
