### ISSUE TITLE
New Discord Link?

### ISSUE THREAD

**Issue by lavaJockey** [AddMGH/Undertale-3DS#17]
Title

**Comment by AddMGH** [comment]
aOH SHIT FUCK AWAO

**Comment by AddMGH** [comment]
tdZCKAA

**Comment by AddMGH** [comment]
https://github.com/AddMGH/Undertale-3DS/wiki/Frequently-Asked-Questions

**Comment by Express76** [comment]
https://discord.gg/yc4bn
