### ISSUE TITLE
When you meet Chara, you shouldn't be able to escape it in any way

### ISSUE THREAD

**Issue by Kulkinz** [AddMGH/Undertale-3DS#6]
Even if you turn off the 3DS during Chara, you should be able to get out of it. It could be done by having a boolean like charaScene, and set it to true while in the scene, and only have it false when the scene is done. Then at the game start, before any title screen, it checks if charaScene is true, and if it is, automatically takes you back to the scene. You could also have some special text talking about how "you tried to escape". It would be a way to ensure that no one can escape Chara after you activate the scene.

**Comment by AddMGH** [comment]
This is already going to be a thing, charaScene is a required line of code as it tells the 3DS where you are.
