### ISSUE TITLE
The intro is broken in multiple ways

### ISSUE THREAD

**Issue by ToransuShojo** [AddMGH/Undertale-3DS#8]
The introduction has multiple problems with it. The first is it's lack of music or sound. I did see unused code regarding music, so this is most likely an easy fix. Secondly, pressing the A button is interpreted as a hold, forcing the images to scroll at a rapid pace until you release the button. This can result in several images being passed within half of a second of an A press. Finally, the intro images do not scroll on their own.

**Comment by ToransuShojo** [comment]
Pressing A has been resolved with the new pull request. However, another issue has been encountered. Reaching the chara_b point in the intro causes a game crash, due to all variables being local. It is overwritten in undertale.lua, causing a crash (per my understanding). Maybe make variables local?

**Comment by AddMGH** [comment]
Yes, 'chara_b" is rewritten that variable and any others that conflict will need to be local.

**Comment by AddMGH** [comment]
The reason intro.lua is broken so severely is that it was built as a prototype for the intro.
_and my spaghetti code too._

**Comment by ToransuShojo** [comment]
The intro has been fixed and runs properly without errors. The main issue is now main.lua.
